name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
      with:
        dotnet-version: 2.2.108
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
    - name: Test with dotnet
      run: dotnet test 
    
